### ISSUE TITLE
Add more dev tools

### ISSUE THREAD

**Issue by sibylobodoekwe** [risenW/random-abcs#4]
- Add the Base64 page in src/pages.
- Add the Cloud Code page in src/pages.
- Add the JSON Validator page in src/pages.

**Comment by risenW** [comment]
@sibylobodoekwe Add more description on what these do

**Comment by sibylobodoekwe** [comment]
**Base64** is an encoding scheme for converting binary data into a text format that can be safely transmitted over text-based protocols. Represents binary data in an ASCII string format
**Cloud Code** is a server-side code or scripts running on cloud computing platforms for scalable and managed execution of server-side logic. Allows developers to build/deploy server-side logic; handling API requests, data processing, background tasks, etc in a scalable and managed environment provided by the cloud platform.
**JSON Validator** parse and analyze JSON data, checking for errors, missing or invalid keys, incorrect data types, and other syntax-related issues.
