### ISSUE TITLE
Add/link github page in Nav bar

### ISSUE THREAD

**Issue by risenW** [risenW/random-abcs#6]
## Task
* Replace the `suggest a feature` link in Nav bar with a link to github
* Update the name to `Contribute`

**Comment by Joywin2412** [comment]
Hey! I'm ready to work on this issue. Could you please assign me this?

**Comment by risenW** [comment]
> Hey! I'm ready to work on this issue. Could you please assign me this?

Sure, go for it.

**Comment by Joywin2412** [comment]
I have worked on the respective issue. Do review it
